### ISSUE TITLE
Glimpse unexpected context value at location 

### ISSUE THREAD

**Issue by bonesoul** [Glimpse/Home#106]
my setup;
node 7.10.0
express

i'm getting the error;

```
Glimpse (Error UnexpectedContextValue): Glimpse unexpected context value at location ExpressInspectorActionRouteView::onRenderComplete().  Expecting context ID 449f9710396111e7b1d943cd3a3b175d.  Actual context ID is undefined
Glimpse (Error UnexpectedContextValue): Glimpse unexpected context value at location ExpressInspectorActionRouteView::onResponseSend().  Expecting context ID 449f9710396111e7b1d943cd3a3b175d.  Actual context ID is undefined
15/5 14:25:58 [5436] - error: uncaught exception: TypeError: Cannot read property 'hudScriptTemplate' of undefined
    at ScriptManager.hudScript (E:\Coding\vapingdb\node_modules\@glimpse\glimpse-agent-node\release\messaging\ScriptManager.js:59:42)
    at ScriptManager.getScriptTagsForCurrentRequest (E:\Coding\vapingdb\node_modules\@glimpse\glimpse-agent-node\release\messaging\ScriptManager.js:69:38)
    at ExpressInspectorActionRouteView.onResponseSend (E:\Coding\vapingdb\node_modules\@glimpse\glimpse-agent-node\release\inspectors\ExpressInspectorActionRouteView.js:219:50)
    at Object.listener (E:\Coding\vapingdb\node_modules\@glimpse\glimpse-agent-node\release\inspectors\ExpressInspectorActionRouteView.js:32:23)
    at Tracing.publish (E:\Coding\vapingdb\node_modules\@glimpse\glimpse-agent-node\release\tracing\Tracing.js:31:26)
    at ServerResponse.sendResponse [as send] (E:\Coding\vapingdb\node_modules\@glimpse\glimpse-agent-node\release\tracing\module_instrumentors\ExpressProxyActionRouteView.js:70:35)
    at E:\Coding\vapingdb\node_modules\express-beautifier\index.js:31:15
    at onRenderComplete (E:\Coding\vapingdb\node_modules\@glimpse\glimpse-agent-node\release\tracing\module_instrumentors\ExpressProxyActionRouteView.js:99:13)
    at E:\Coding\vapingdb\node_modules\nunjucks\src\environment.js:23:23
    at RawTask.call (E:\Coding\vapingdb\node_modules\asap\asap.js:40:19)
    at flush (E:\Coding\vapingdb\node_modules\asap\raw.js:50:29)
    at wrappedCallback (E:\Coding\vapingdb\node_modules\@glimpse\glimpse-agent-node\release\async-track\async-track.js:293:33)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
GET /glimpse/client/bundle.e78aeaa6b5f621770df8.js 200 1.058 ms - 479447
GET /glimpse/client/dll.vendor.bc419e69c94c30ec7d62.js 200 1.027 ms - 1746579
```

**Comment by mike-kaufman** [comment]
Thanks @bonesoul.  Is there any chance you can get us a small project that reporoduces this error?  It would be super helpful for us.

Some brief background: To correlate events to the correct http request requires that we propogate state across async call boundaries.  e.g., if you register an event handler on a request (`req.on('data', () => console.log('got some data'))`, we need to know which http request if in play when that handler is invoked.  There's a lot of complexity in this, and it can be complicated by other packages you've loaded.  The easiest way for us to get traction on this is to have a sample project that repros the issue. 

Thanks so much for reporting this!

**Comment by mike-kaufman** [comment]
@bonesoul - two requests if you don't mind:

1.  We just pushed up a new release onto npm (version 0.21.5).  If you could give this a try at some point & let us know if you're still seeing these errors?

2.  If not if you could provide any additional context on what's happening here.  E.g., are you using something like redis, mysql or postgres?  A specific promise library?

**Comment by bonesoul** [comment]
using;
* mongodb 3.4.x
* node 8.0.0
* using bluebird as promise library.

i'll try the new version now and report the outcome.
