### ISSUE TITLE
TypeError: Cannot assign to read only property 'createGzip' of object '#<Object>'

### ISSUE THREAD

**Issue by serge1peshcoff** [Glimpse/Home#118]
I'm facing this error on server startup, the app just crashes and that's it:

```
/all/Documents/Programming/csgocombo/node_modules/@glimpse/glimpse-agent-node/release/async-track/async-track.js:244
                            pkg[prop] = this.instruCbReg(config, prop, pkg[prop], newPath);
                                      ^

TypeError: Cannot assign to read only property 'createGzip' of object '#<Object>'
    at AsyncTrack.instrument (/all/Documents/Programming/csgocombo/node_modules/@glimpse/glimpse-agent-node/release/async-track/async-track.js:244:39)
    at Module.asyncTrackRequire [as require] (/all/Documents/Programming/csgocombo/node_modules/@glimpse/glimpse-agent-node/release/async-track/async-track.js:112:26)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/all/Documents/Programming/csgocombo/node_modules/request/request.js:8:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

Node 8.1.0, Xubuntu Studio 17.04 Zesty x64.
Can provide any necessary information if needed, just ask.

**Comment by serge1peshcoff** [comment]
Whoops, just noticed it's a duplicate, sorry for that.

**Comment by nikmd23** [comment]
No problem @serge1peshcoff!

We'd love to have a chat with you about how you're using Glimpse, what's useful and what isn't. It shouldn't take more than 30 mins and there's no need to prepare in advance. If you're interested, just pick a time slot over at https://calendly.com/nikmd23/30min

Thanks!

**Comment by serge1peshcoff** [comment]
@nikmd23 well I'm not using it yet because of the lack of Node.js v8 support :D
But when I'll use it, I'd definitely look into it.
